genome: "dm6"
ensembl_genome_build: "110"
extra: "" # extra argument for damidseq_pipeline
fusion_genes: FBgn0038542,FBgn0085506 # Genes from these proteins will be removed from the analysis
deeptools:
  matrix: # Settings for computeMatrix
    mode: scale-regions # scale-regions or reference-point
    referencePoint: TSS # TSS, TES, center (only for reference-point mode)
    regionBodyLength: 6000
    upstream: 3000
    downstream: 3000
    binSize: 10
    averageTypeBins: mean
    regionsFileName: "" # BED or GTF file(s) with regions of interest (optional, whole genome if not specified)
    no_whole_genome: False # If True, will omit whole genome as region and only use regionsFileName(s)
    extra: "" # Any additional parameters for computeMatrix
  plotHeatmap:
    interpolationMethod: auto
    plotType: lines # lines, fill, se, std
    colorMap: viridis # https://matplotlib.org/2.0.2/users/colormaps.html
    alpha: 1.0
    extra: "" 
peak_calling:
  seed: 1234
  iterations: 100 # N argument
  fdr: 0.01
  extra: ""
  overlapping_peaks:
    max_size: 10 # Maximum size of peaks to be extended
    extend_by: 40 # Number of bp to extend peaks on either side
    keep: 2 # Minimum number peaks that must overlap to keep
motif_analysis: # With findMotifsGenome.pl from Homer
  run_analysis: True
  len: 8,10,12 # Motif length
  mask: "-mask" # Mask repeat sequences (leave empty for no masking)
  extra: "" # Extra arguments for findMotifsGenome.pl
enrichment_analysis:
  libraries: "GO_Biological_Process_2023,GO_Molecular_Function_2023,Reactome_2022"
resources: # computing resources
  trim:
    cpu: 8
    time: 60
  fastqc:
    cpu: 4
    time: 60
  damid:
    cpu: 8
    time: 120
  index:
    cpu: 36
    time: 60
  deeptools:
    cpu: 8
    time: 90
  plotting:
    cpu: 2
    time: 20
