genome: dm6
ensembl_genome_build: 110
plasmid_fasta: none
fusion_genes: FBgn0038542,FBgn0085506 # Genes from these proteins will be removed from the analysis
bowtie2:
  extra: ""
damidseq_pipeline:
  binsize: 300
  extra: "" # extra argument for damidseq_pipeline
deeptools:
  bamCoverage: # bam to bigwig conversion for QC
    binSize: 10
    normalizeUsing: RPKM
    extra: ""
  matrix: # Settings for computeMatrix
    mode: scale-regions # scale-regions or reference-point
    referencePoint: TSS # TSS, TES, center (only for reference-point mode)
    regionBodyLength: 6000
    upstream: 3000
    downstream: 3000
    binSize: 10
    averageTypeBins: mean
    regionsFileName: "" # BED or GTF file(s) with regions of interest (optional, whole genome if not specified)
    no_whole_genome: False # If True, will omit whole genome as region and only use regionsFileName(s)
    extra: "" # Any additional parameters for computeMatrix
  plotHeatmap:
    interpolationMethod: auto
    plotType: lines # lines, fill, se, std
    colorMap: viridis # https://matplotlib.org/2.0.2/users/colormaps.html
    alpha: 1.0
    extra: "" 
peak_calling_perl:
  run: True
  iterations: 5 # N argument
  fdr: 0.01
  fraction: 0 # Fraction of random fragments to consider per iteration
  min_count: 2 # Minimum number of reads to consider a peak
  min_quantile: 0.95 # Minimum quantile for considering peaks
  step: 0.01 # Stepping for quantiles
  unified_peaks: max # Method for calling peak overlaps. 'min': call minimum overlapping peak area. 'max': call maximum overlap as peak
  extra: ""
  overlapping_peaks:
    max_size: 10 # Maximum size of peaks to be extended
    extend_by: 40 # Number of bp to extend peaks on either side
    keep: 2 # Minimum number peaks that must overlap to keep
peak_calling_macs2:
  run: False
  mode: narrow
  qvalue: 0.05
  broad_cutoff: 0.1
  extra: ""
resources: # computing resources
  trim:
    cpu: 8
    time: 60
  fastqc:
    cpu: 4
    time: 60
  damid:
    cpu: 24
    time: 720
  index:
    cpu: 36
    time: 60
  deeptools:
    cpu: 8
    time: 90
  plotting:
    cpu: 2
    time: 20
